---
title: "Disabled_data"
author: "Simona Bisiani"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Disabled data

Analysing ISTAT data on disabilities. Extracted from disabilitaincifre.it

```{r importing data, echo = FALSE}
library(readxl)
library(tidyverse)
library(janitor)

tbl <-
     list.files(pattern = "*.xls")

tbl <- lapply(tbl, read_excel)

for (i in 1:length(tbl)){
  name[i] <- first(colnames(tbl[[i]]))
  names(tbl)[i] <- name[i]
  names(tbl)[i] <- str_replace(name[i], ".*Anno", "")
  column_names <- tbl[[1]][3,]
  colnames(tbl[[i]]) <- column_names
}


share_persons_disabilites_09_19_regions <- map_dfr(tbl, bind_rows, .id = "id") %>% 
  select(-3) %>% 
  rename('regione' = ...1) %>% 
  filter(!is.na(regione) & regione != "REGIONI") %>% 
  mutate(id = gsub("\\.","",id),
         id = as.numeric(gsub(" ", "", id)))

library(RColorBrewer)
nb.cols <- 21
mycolors <- colorRampPalette(brewer.pal(8, "Set3"))(nb.cols)

ggplot(share_persons_disabilites_09_19_regions, aes(id, as.numeric(`Limitazioni gravi`), color = regione)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = mycolors) + 
  theme_minimal() +
  labs(y = "% persone con Limitazioni gravi", x = "anno")

```

## 